package ace.actually.dataplanets.space;

import net.minecraft.nbt.CompoundTag;
import org.apache.commons.io.FileUtils;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import java.util.UUID;

//TODO: reimplement this if we are going to continue to use GCYR.
public class StarSystemRebuilder {

    public static void buildRPFromData(CompoundTag tagIn)
    {
        String LOCLOC = Path.of("./").toAbsolutePath()+"\\resourcepacks\\";

        for(String system: tagIn.getAllKeys())
        {
            CompoundTag tag = tagIn.getCompound(system);

            String uuid = UUID.randomUUID().toString();
            String systemName = tag.getString("systemName");
            List<String> solar_system = List.of("{\n" +
                    "  \"galaxy\": \"gcyr:milky_way\",\n" +
                    "  \"solar_system\": \"dataplanets:SW\",\n".replace("SW",systemName) +
                    "  \"sun\": \"gcyr:textures/sky/sunmenu.png\",\n" +
                    "  \"sun_scale\": 60,\n" +
                    "  \"button_color\": 4284861158,\n" +
                    "  \"ring_color\": 3357815419\n" +
                    "}");



            try {
                FileUtils.writeLines(new File(LOCLOC+"pack"+uuid+"\\assets\\dataplanets\\gcyr\\planet_assets\\solar_systems\\"+systemName+".json"),solar_system);
                FileUtils.writeLines(new File(LOCLOC+"pack"+uuid+"\\pack.mcmeta"), List.of("""
                    {
                    \t"pack": {
                    \t\t"description": "Generated by Dataplanets",
                    \t\t"pack_format": 34
                    \t}
                    }"""));

            } catch (IOException e) {
                throw new RuntimeException(e);
            }

            StringBuilder langFile = new StringBuilder("{\"dataplanets.").append(systemName).append("\":\"");
            String rebuild = systemName.toUpperCase();
            rebuild = rebuild.substring(0,2)+" "+rebuild.substring(2);
            langFile.append(rebuild).append("\",");
            for(String key: tag.getAllKeys())
            {
                if(!tag.getCompound(key).isEmpty())
                {
                    CompoundTag planetData = tag.getCompound(key);
                    String planetName = planetData.getString("name");
                    List<String> planet_rings = List.of("{\n" +
                            "  \"galaxy\": \"gcyr:milky_way\",\n" +
                            "  \"solar_system\": \"dataplanets:SOMEWHERE\",\n".replace("SOMEWHERE",systemName) +
                            "  \"texture\": \"gcyr:textures/sky/deimos.png\",\n" +
                            "  \"speed\": S,\n".replace("S",""+planetData.getInt("yearDays")) +
                            "  \"scale\": S,\n".replace("S",""+planetData.getInt("scaleClient")) +
                            "  \"radius\": X\n".replace("X",""+planetData.getFloat("radiusClient")) +
                            "}");

                    List<String> sky_renderer = List.of("{\n" +
                            "  \"world\": \"dataplanets:SW\",\n".replace("SW",planetName) +
                            "  \"stars\": {\n" +
                            "    \"fancy_count\": 13000,\n" +
                            "    \"fast_count\": 6000,\n" +
                            "    \"colored_stars\": true,\n" +
                            "    \"daylight_visible\": true\n" +
                            "  },\n" +
                            "  \"sunset_color\": \"none\",\n" +
                            "  \"dimension_effects\": {\n" +
                            "    \"type\": \"none\"\n" +
                            "  },\n" +
                            "  \"cloud_effects\": \"none\",\n" +
                            "  \"weather_effects\": \"none\",\n" +
                            "  \"horizon_angle\": 0,\n" +
                            "  \"sky_objects\": [\n" +
                            "    {\n" +
                            "      \"texture\": \"gcyr:textures/sky/sun.png\",\n" +
                            "      \"blending\": true,\n" +
                            "      \"render_type\": \"dynamic\",\n" +
                            "      \"scale\": SZ,\n".replace("SZ",""+(planetData.getInt("solarPower")+1)) +
                            "      \"rotation\": [\n" +
                            "        0.0,\n" +
                            "        -90.0,\n" +
                            "        0.0\n" +
                            "      ]\n" +
                            "    }\n" +
                            "  ]\n" +
                            "}");

                    langFile.append("\"level.").append(planetName).append("\":\"");
                    rebuild = planetName.toUpperCase();
                    rebuild = rebuild.substring(0,2)+" "+rebuild.substring(2,rebuild.length()-1)+" "+rebuild.toLowerCase().charAt(rebuild.length()-1);
                    langFile.append(rebuild).append("\",");

                    try {
                        FileUtils.writeLines(new File(LOCLOC+"pack"+uuid+"\\assets\\dataplanets\\gcyr\\planet_assets\\planet_rings\\"+systemName+"\\"+planetName+".json"),planet_rings);
                        FileUtils.writeLines(new File(LOCLOC+"pack"+uuid+"\\assets\\dataplanets\\gcyr\\planet_assets\\sky_renderers\\"+planetName+".json"),sky_renderer);
                        FileUtils.writeLines(new File(LOCLOC+"pack"+uuid+"\\assets\\dataplanets\\lang\\en_us.json"),List.of(langFile.substring(0,langFile.length()-1)+"}"));

                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                }
            }
            try {
                FileUtils.writeLines(new File(LOCLOC+"pack"+uuid+"\\assets\\dataplanets\\lang\\en_us.json"),List.of(langFile.substring(0,langFile.length()-1)+"}"));
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }

    }
}
